### ISSUE TITLE
Type "ZBLAME_PART_REF_T" is unknown.

### ISSUE THREAD

**Issue by rjbhayani** [abapinho/abapBlame#62]
![image](https://user-images.githubusercontent.com/19501487/107536868-45a5a380-6be8-11eb-92ef-15d086237b00.png)

**Comment by nununo** [comment]
That's odd... because that object is part of the repository. Can you check if the object exists in your system but is inactive for some reason? What does ZABAPGIT say about that particular object? Thanks.

**Comment by rdibbern** [comment]
@nununo the object seems to be inactive once you pull it

**Comment by nununo** [comment]
Hi @rdibbern @rjbhayani,

I tried to do a fresh install and indeed `ZBLAME_PART_REF_T` ends up inactive. I had to activate it manually.

I fear this may be related to the order by which `abapGit` activates objects. Because this table type references a class. Actually I just upgraded `abapGit` to its latest version and 2 of its objects also stayed inactive and I had to manually activate them.

The good news is that the solution is simple: activate the object manually.

Thank you for finding this problem and sorry that I can't provide a solution. I will open an issue in `abapGit` hoping they find a solution for it.

Regards,
Nuno

**Comment by nununo** [comment]
I closed the issue since it is caused by external sources.

**Comment by nununo** [comment]
After I reported this issue [here](https://github.com/abapGit/abapGit/issues/4513), @larshp suggested a work-around which consists in replacing DDIC object `ZBLAME_PART_REF_T` with a type declared in a class and pointed to [this issue](https://github.com/abapGit/abapGit/issues/606).

I will reopen this issue and do as suggested. This will prevent this problem from happening.

**Comment by larshp** [comment]
plus leaves a smaller footprint in ddic

**Comment by nununo** [comment]
2e49b866146f9d6dc35589de42c67f48691ac3d4 replaces `ZBLAME_PART_REF_T` with an inline type to avoid `abapGit` activation issues.
