### ISSUE TITLE
ITAB_DUPLICATE_KEY in  zcl_blame_parts->get_requests

### ISSUE THREAD

**Issue by rdibbern** [abapinho/abapBlame#63]
Hi,

we have received a `ITAB_DUPLICATE_KEY` dump while `zcl_blame_parts->get_requests( )` is called by `zcl_blame_parts->get_data()`. 

```abap
rt_request = VALUE #( BASE rt_request               
       ( request = <t_group>-request                    
         description = NEW zcl_blame_request( <t_group>-request )->description               
         author = <t_group>-author                            
         name = <t_group>-name                             
         line_count = lines( t_request )                             
         blame_percentage = lines( t_request ) / lines( t_line ) ) ).
``` 
It seems that our task for each user is not considered here. Hence I have locally changed the primary key of the table type `zblame_request_info_t` and appended the field `author` as well. Not sure if this is really correct, but the task is not part of the table.

Regards,

**Comment by nununo** [comment]
Thank you @rdibbern for finding this bug! I'll look into it as soon as possible.

**Comment by nununo** [comment]
> It seems that our task for each user is not considered here. Hence I have locally changed the primary key of the table type `zblame_request_info_t` and appended the field `author` as well. Not sure if this is really correct, but the task is not part of the table.

Well, the objective here is to have one line per request. If you add the author to the private key, you'll potentially end up with more than one line with the same request.

I believe this is probably a regression that happened when tasks were introduced. Before that, I think the author was always the one from the request.

Since the request's owner information is not that relevant and can even be misleading, I'll just get rid of it. That should solve the problem ;-)

**Comment by nununo** [comment]
@rdibbern I have corrected it as explained above. Can you please check and let me know if it's working now? Thanks!

**Comment by rdibbern** [comment]
Thanks @nununo. It seems to work now.
